Use 'hatch version' instead of manually updating the version
ansible-community/antsibull-changelog pull request #133
Opened 2023-09-27 17:56 UTC by felixfontein

We did this change to antsibull-docs some time ago. I had to fix that a bit today with https://github.com/ansible-community/antsibull-docs/commit/676780b99912f5e9d8b206b14a65ed03d8405919. This PR applies the noxfile changes to this project as well.

2024-01-28 08:29 UTC, felixfontein commented
Restart CI.

2024-01-31 20:19 UTC, gotmax23 requested changes
Make sure you switch the `git add` commands to add the `__init__.py` file instead of `pyproject.toml` after bumping the version.

2024-02-07 03:06 UTC, gotmax23 commented on noxfile.py
>      session.run("antsibull-changelog", "release")
```
nox > antsibull-changelog release
ERROR You need to explicitly specify the version for other projects with --version
nox > Command antsibull-changelog release failed with exit code 5
nox > Session bump failed.
```

```suggestion
    session.run("antsibull-changelog", "release", "--version", version)
```

2024-02-08 15:35 UTC, felixfontein commented on noxfile.py
>      session.run("antsibull-changelog", "release")
Oh right, antsibull-changelog doesn't do magic :facepalm:

2024-02-08 18:52 UTC, gotmax23 approved these changes

2024-02-08 19:10 UTC, gotmax23 commented on noxfile.py
>      session.run("antsibull-changelog", "release")
See https://github.com/ansible-community/antsibull-changelog/pull/141 :)

2024-02-08 19:36 UTC, merged

2024-02-08 19:36 UTC, felixfontein commented
@gotmax23 thanks for reviewing and testing!